added debugging info

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -14,14 +14,18 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    - name: Verify context
+      run: |
+        ls -la
+        test -f cmd/web/main.go && echo "main.go found" || echo "main.go NOT found"
+        ls -la cmd/ || echo "cmd/ not found"
+        ls -la cmd/web/ || echo "cmd/web/ not found"
     - name: Create credentials.env
       run: |
         echo "WEB_DB_LINK=${{ secrets.TTCOMPANION_DB_LINK }}" > credentials.env
         echo "JWT_SECRET_KEY=${{ secrets.TTCOMPANION_JWT_SECRET_KEY }}" >> credentials.env
         echo "DB_NAME=${{ secrets.TTCOMPANION_DB_NAME }}" >> credentials.env
         echo "API_URL=${{ secrets.TTCOMPANION_API_URL_RENDER }}" >> credentials.env
-    - name: List files in workspace
-      run: ls -laR
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
